# Generated by Django 6.0.5 on 2026-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
